### ISSUE TITLE
你好 ios15 copy捷径似乎不稳定 一会能用一会不能用

### ISSUE THREAD

**Issue by h605290713** [YanxinTang/clipboard-online#12]
你好 ios15 copy捷径似乎不稳定 一会能用一会不能用

**Comment by h605290713** [comment]
我在最后加了一条获取剪贴板好了 不知道不是15的bug

**Comment by YanxinTang** [comment]
我这边没有出现这个问题

**Comment by h605290713** [comment]
> 我这边没有出现这个问题

我也起奇怪 另一台手机14.8没问题  然后主力机15 就不行了 工具点个赞好用 反向推相当方便 啥时候能支持文件系统就6了

**Comment by YanxinTang** [comment]
目前是支持小文件复制的

**Comment by h605290713** [comment]
> 目前是支持小文件复制的

怎么用 🤦‍♀️

**Comment by YanxinTang** [comment]
直接复制图片就好，和文本一样的操作方式。
