### ISSUE TITLE
请求超时

### ISSUE THREAD

**Issue by mumuxi-git** [YanxinTang/clipboard-online#15]
好像部分WiFi不支持，比如有些地方的WiFi需要登录，就无法连接，提示请求超时，但用其他WiFi或手机热点是OK的，不知道是怎么回事？

**Comment by YanxinTang** [comment]
需要登录的这种 wifi 没有测试过，要确保手机和电脑之间 http 能通。

**Comment by mumuxi-git** [comment]
请问http怎么测试呢？

**Comment by YanxinTang** [comment]
手机浏览器访问 `http://<电脑IP>:8086` 看看有没有响应。

**Comment by mumuxi-git** [comment]
没有响应，用手机谷歌浏览器测试，输入`IP:8086`，提示无法访问此网站，响应时间过长。
