### ISSUE TITLE
PC图片无法推送到IOS

### ISSUE THREAD

**Issue by chenqinru** [YanxinTang/clipboard-online#19]
手机图片可以推送到PC，但是PC图片无法推送到IOS

**Comment by YanxinTang** [comment]
是在哪里粘贴不行的呢

**Comment by chenqinru** [comment]
> 是在哪里粘贴不行的呢

电脑推送到ios上，一定要ctrl + x剪切，ctrl + c复制不行。
如果电脑上误按ctrl + c复制之后，手机上用快捷指令接收的话，手机粘贴一直是空。

**Comment by YanxinTang** [comment]
在哪个 app 粘贴的呢？我自己用微信和备忘录可以

还有，在捷径中看一下剪切板的权限有没有
