### ISSUE TITLE
authkey 有什么特殊要求吗？

### ISSUE THREAD

**Issue by xiozf** [YanxinTang/clipboard-online#2]
clipboard-online 0.2.0，win7 x64 。
测试纯数字和纯字母比如：aa、123、123456，每次修改完都重启程序。粘贴提示：操作被拒绝，authkey 验证失败。复制也失败，无提示。
取消 authkey 后均正常。

**Comment by YanxinTang** [comment]
捷径里面设置 authkey 了吗？

**Comment by xiozf** [comment]
同步设置的。电脑改手机就跟着改。6s 13.7 。

**Comment by YanxinTang** [comment]
尴尬，把计算时间戳的两个日期写反了

![image](https://user-images.githubusercontent.com/15326923/101583511-9517f980-3a16-11eb-88c3-f676b7213d77.jpeg)

先临时用空字符串，晚上更新一下捷径。

**Comment by xiozf** [comment]
原来如此，调换顺序后可以了。
