### ISSUE TITLE
快捷指令两个循环都无法运转完成，卡在了中间无法执行完

### ISSUE THREAD

**Issue by Kobe-Bryant-8** [YanxinTang/clipboard-online#20]

**Comment by YanxinTang** [comment]
是复制什么内容，文本还是文件？还有就是在浏览器访问 `http://ip:8086` 看看有无响应，诊断一下是否是网络问题

**Comment by Kobe-Bryant-8** [comment]
在电脑上打开访问这个地址显示 {"error":"接口版本不匹配，请升级您的捷径"} iphone和ipad上的浏览器都打不开这个地址

**Comment by YanxinTang** [comment]
手机和电脑间网络不通，请检查一下是否是防火墙的问题。
