### ISSUE TITLE
疑似Bug

### ISSUE THREAD

**Issue by 0xHertz** [YanxinTang/clipboard-online#21]
升级windows11之后，无法运行windows端的`clipboard-online.exe`，不知道什么原因

目前已知信息是
> 双击运行后，会运行`com surrogate`程序
   我查了一下，这是windows的com代理程序`dllhost.exe`，
   确定是由`clipboard-online.exe`创建的

> 可以确定端口8086并没有被其他程序占用

无法运行的原因还找不到，请问这是我的问题还是程序bug

**Comment by 0xHertz** [comment]
.。。。今天再次测试，又可以运行了。。。
原因依旧未知

**Comment by YanxinTang** [comment]
我的也是 Windows11，不过没碰到过这个问题。晚上回去再试试。

**Comment by YanxinTang** [comment]
我在 Windows 11 并没有复现，所以这个 issue 准备关闭。
