### ISSUE TITLE
ios 15.1

### ISSUE THREAD

**Issue by h605290713** [YanxinTang/clipboard-online#22]
![f17c8ec7d2e3ee58898785afb9886d5](https://user-images.githubusercontent.com/22915509/143517284-14111256-481c-4585-9170-af91c86ef5de.jpg)

有的图片上传会出现这个错误 有的不会  ios 15.1

**Comment by YanxinTang** [comment]
可以粘一张出现错误的图片上来吗？

**Comment by h605290713** [comment]
> 可以粘一张出现错误的图片上来吗？

![图像](https://user-images.githubusercontent.com/22915509/143543332-bd83ffc2-6eb3-437d-af38-03a76c4dbdef.jpeg)

我有发现一个问题 我把图片放到备忘录 轻点然后共享可以上传出来 在相册反而不行

**Comment by YanxinTang** [comment]
从相册中分享图片时确实有这个问题

**Comment by h605290713** [comment]
我又发现一个 有的视频发送了 会提示加密

**Comment by YanxinTang** [comment]
图片这个查了一下，是 iOS的沙盒限制 ，暂时无解，如果有需要先拷到剪切板上粘贴吧。
视频我自己粘了几个都没有出现加密的提示，能否描述一下视频来源。

**Comment by HsWand** [comment]
> 图片这个查了一下，是 iOS的沙盒限制 ，暂时无解，如果有需要先拷到剪切板上粘贴吧。
> 视频我自己粘了几个都没有出现加密的提示，能否描述一下视频来源。

之前做过一个类似的捷径，也有类似的问题，我添加了一步把共享菜单输入的照片拷贝到剪贴板，再利用剪贴板做后续操作，就可以跳过这个沙盒机制。

**Comment by HsWand** [comment]
> 图片这个查了一下，是 iOS的沙盒限制 ，暂时无解，如果有需要先拷到剪切板上粘贴吧。
> 视频我自己粘了几个都没有出现加密的提示，能否描述一下视频来源。

在大佬的基础上修改了一下快捷指令，测试后照片上传正常。本人编程小白一只，不知这样处理会有什么bug之类的，不吝赐教。感谢大佬提供的好工具给我们带来便利！祝好！
![Uploading 7746ACBF-F1A5-4EF2-8784-C79D976373FB.png…]()

**Comment by HsWand** [comment]
![23054221-9EEA-47A0-B99E-62B6C2545842](https://user-images.githubusercontent.com/31243816/151018520-f70da092-556d-43a4-b3d6-fc2efd3ac8a4.png)

**Comment by HsWand** [comment]
![7FF90E7A-1AB2-4594-9B59-360F8D28CA16](https://user-images.githubusercontent.com/31243816/151018829-48e4bd11-e34b-4fb8-8870-f64620e3c06c.jpeg)

**Comment by YanxinTang** [comment]
好想法，我回头更新一下！
