### ISSUE TITLE
ios15.2到win11 22000.376

### ISSUE THREAD

**Issue by inkayn** [YanxinTang/clipboard-online#24]
使用v0.2.6版本从ios端发送剪切板中的文字到PC时ios端会在最后一步“获取URL内容”中卡住并显示请求超时
获取电脑剪切板时仍会出现该问题，ip地址和wifi名称均没问题，ios端和电脑端均设置了DHCP外的静态ip并能正常使用
电脑端的log.txt中无内容
想来请教一下问题出在哪里，谢谢！

**Comment by inkayn** [comment]
同时v0.2.6在win11任务栏中无图标显示，
v0.2.5有图标显示

**Comment by YanxinTang** [comment]
根据你的描述，应该是 pc 的程序没有启动成功，可以根据以下几个步骤排查一下：

1. 手动运行 pc 程序，如果出现报错，打开任务管理器找一下是不是已经有在运行的程序了，如果有，杀掉再启动一下
2. 第一步确保程序启动之后，在手机上用浏览器访问 `http://<ip>:8086` 看看有没有响应

**Comment by inkayn** [comment]
不管是双击运行还是以管理员身份运行在任务管理器里都找不到clipboard开头的进程，不过在目录里能正常生成log.txt以及confit.json文件

**Comment by inkayn** [comment]
刚才在运行之后，log.txt显示了一下内容

time="2021-12-17T21:47:39+08:00" level=fatal msg="failed to create applicaton" error="Shell_NotifyIcon\n\nStack:\ngoroutine 1 [running, locked to thread]:\nruntime/debug.Stack(0x4, 0xc00029fa70, 0x0)\n\tC:/hostedtoolcache/windows/go/1.15.15/x64/src/runtime/debug/stack.go:24 +0xa5\ngithub.com/lxn/walk.newErr(...)\n\tC:/Users/runneradmin/go/pkg/mod/github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/error.go:81\ngithub.com/lxn/walk.newError(0x15740a1, 0x10, 0xc00029fa00, 0x139f44e)\n\tC:/Users/runneradmin/go/pkg/mod/github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/error.go:85 +0x2d\ngithub.com/lxn/walk.NewNotifyIcon(0x1655a60, 0xc000244c00, 0x0, 0xc000148758, 0xc000305920)\n\tC:/Users/runneradmin/go/pkg/mod/github.com/lxn/walk@v0.0.0-20210112085537-c389da54e794/notifyicon.go:110 +0x318\nmain.NewApplication(0x1a1ca40, 0x1635e40, 0xc000148758, 0xc0000001a4)\n\tD:/a/clipboard-online/clipboard-online/app.go:71 +0x9e\nmain.main()\n\tD:/a/clipboard-online/clipboard-online/main.go:55 +0x56\n"

**Comment by YanxinTang** [comment]
我自己的 win 11 并没有出现过这个问题，等我装个虚拟机再测试一下。

**Comment by inkayn** [comment]
您好 我重启电脑之后 目前已可以正常运行 虽然不清楚原因 能用就行 麻烦您啦！
