### ISSUE TITLE
win11下显示http server 启动失败

### ISSUE THREAD

**Issue by dijian1997** [YanxinTang/clipboard-online#25]
![360截图1649121011614298](https://user-images.githubusercontent.com/19221717/147556520-d948bb72-8cf1-4f3c-99ea-96f1cf13437a.png)
不能成功运行exe文件

**Comment by YanxinTang** [comment]
`netstat -ano | findstr 8086`

看一下是不是端口被占用了

**Comment by dijian1997** [comment]
该如何检查呢，这方面不是很擅长

**Comment by YanxinTang** [comment]
![image](https://user-images.githubusercontent.com/15326923/147563599-b91cb6c6-4885-471e-83d2-d29346e01108.png)

**Comment by dijian1997** [comment]
问题已解决，疑似是我的防火墙进出规则的原因

**Comment by CSnoobiee** [comment]
> 问题已解决，疑似是我的防火墙进出规则的原因

你好，请问你怎么解决的呢？我的也是这个防火墙问题

**Comment by Eureka0092-edu1** [comment]
> > 问题已解决，疑似是我的防火墙进出规则的原因
> 
> 你好，请问你怎么解决的呢？我的也是这个防火墙问题

在搜索中搜防火墙和网络保护，点地下允许应用通过防火墙中，再点更改，把clipboard-online的所有都勾选上，就能用啦

**Comment by meiyu-uts** [comment]
你好，防火墙更改后还是会跳出启动失败，你的已经完全解决了？
