### ISSUE TITLE
android 使用 tasker 来获取/发送剪贴板

### ISSUE THREAD

**Issue by Befod** [YanxinTang/clipboard-online#26]
https://taskernet.com/shares/?user=AS35m8kc7V%2FmxwnKDX5H5c5GEhNcpFX6F5vfEYKreUNm%2Fpbha4ANWBNPl05tilOk3X4%3D&id=Task%3Aclipboard
点击导入 tasker 即可

**Comment by YanxinTang** [comment]
感谢分享

**Comment by dijian1997** [comment]
好像没有authkey

**Comment by Befod** [comment]
> 好像没有authkey

可以了，需要把禁用的两条启用，也可以把win剪贴板的文件复制到手机上了

**Comment by dijian1997** [comment]
好的，我更新下

**Comment by dijian1997** [comment]
没有找到禁用的条目

**Comment by dijian1997** [comment]
准确来说不知道吧authkey放入条目的那个位置，可以麻烦您简单的说一下具体的key填充位置方便我们小白用户使用吗

**Comment by dijian1997** [comment]
哈哈哈其实是111

**Comment by dijian1997** [comment]
禁用的条目2,3启用后再禁用的条目2%key下的“111”替换为authkey就好了

**Comment by dijian1997** [comment]
获取剪切板仍存在验证问题

**Comment by Befod** [comment]
> 

试下这个
https://tasker.joaoapps.com/userguide/en/help/ah_secure_setting_grant.html

**Comment by dijian1997** [comment]
还是不能调通

**Comment by Befod** [comment]
> 还是不能调通

试了下没问题，重启一下软件试试

**Comment by foolmos** [comment]
@Befod @YanxinTang @dijian1997 大佬们，小众那个教程帖404了，大概猜一下，估计是用http request shortcuts导入json用，现在就缺个json模版抄作业呢😿求大佬共享一下～🙏
