### ISSUE TITLE
显示无法连接服务器

### ISSUE THREAD

**Issue by mGitup** [YanxinTang/clipboard-online#27]
wifi名字和电脑内网地址都配置好了，软件也安的最新的。是用手机的热点

**Comment by YanxinTang** [comment]
检查一下电脑的防火墙？先临时关了试试

**Comment by mGitup** [comment]
刚刚WiFi也试了，重新搞了下指令，结果请求超时。

**Comment by mGitup** [comment]
> 检查一下电脑的防火墙？先临时关了试试

还是不行，而且我是允许该应用通过防火墙的

**Comment by YanxinTang** [comment]
1. 电脑访问 `http://127.0.0.1:8086`，看是否有响应，确保电脑端程序正常运行
2. 手机访问 `http://<pc_ip>:8086`，看是否有响应，确保手机和电脑间网络通畅

**Comment by mGitup** [comment]
> 1. 电脑访问 `http://127.0.0.1:8086`，看是否有响应，确保电脑端程序正常运行
> 2. 手机访问 `http://<pc_ip>:8086`，看是否有响应，确保手机和电脑间网络通畅
我刚刚把ip改成了wlan的ip，又行了，，不是说要填以太网那个内外ip吗。（我之前在一个公众号文章看的）
解决了，麻烦您了，感谢回答，很及时！

**Comment by mGitup** [comment]
咦，我用WiFi可以，刚刚换热点就不行了，又显示无法连接服务器。
难道是因为ios15热点用WPA3的原因？

**Comment by YanxinTang** [comment]
你电脑连热点的话，要填电脑在热点这个局域网的 ip

在捷径里面的词典那再添加一项，热点名称为 key, 热点局域网ip作为 value 来适应这种情况

**Comment by mGitup** [comment]
您好，上次我按照您说的做了，可还是没解决。

最近又需要用手机热点来互通剪切板了，我担心之前下载的版本落后，就在电脑重新下载软件，手机重新加入快捷指令，并只修改了词典，填入了热点名称和电脑局域网ip，遇到了上次一样的问题。

电脑访问http://127.0.0.1:8086显示{"error":"接口版本不匹配，请升级您的捷径"}
手机访问http://<pc_ip>:8086显示无法显示url
软件配置文件和快捷指令里的端口都是8086

我还把热点名称改成全英文试了也不行，不知道问题出在哪里。我之前试过连同一个WiFi是可以的。
期盼您方便的时候能帮我看看，谢谢！

**Comment by YanxinTang** [comment]
有没有检查一下电脑的防火墙呢？

**Comment by mGitup** [comment]
> 有没有检查一下电脑的防火墙呢？

是允许该应用通过防火墙的

**Comment by mGitup** [comment]
我回来连WiFi试，可以。那肯定就是ios热点的问题了

**Comment by RougeWhite** [comment]
好像会出现https://<pc_ip>:8086的状况 从而导致无法获取信息，修改url 原内容 http://【ip】:【port】   为 http://<pc_ip>:8086 就好了
