### ISSUE TITLE
发送/获取图片文件没问题，图像不行。

### ISSUE THREAD

**Issue by xiozf** [YanxinTang/clipboard-online#3]
PC--->手机  
  
1、图片文件：PC微信聊天记录点开任意一张图片，右键—复制。  
    在安卓机和苹果机测试均通过，没问题。  
2、图像：随便截张图。比如打开PC微信聊天界面，点击截图—随便截一张。  
    在安卓机和苹果机测试失败，状态码400。  
  
  
手机--->PC  
  
1、打开ios相册，点开一张图片，点击共享按钮，点击拷贝照片，在捷径中运行粘贴。
    在苹果机测试失败，PC剪贴板得到一堆带换行的字符，用剪贴板管理软件预览效果如下：
![Image 001](https://user-images.githubusercontent.com/1025309/101727818-2c9d4b00-3af0-11eb-80c1-5b3b0f62ba52.png)  
    安卓机还没base64应用测试。

**Comment by YanxinTang** [comment]
目前截图确实不能被拷贝。因为它是bitmap类型，我没有处理这种类型。不过大概知道怎么去做，后面应该会先开发这个。

手机 -> PC：这个问题没有复现。你分享的照片是什么格式的？

目前的版本 手机 -> PC 粘贴文件时，因为我只处理了windows剪切板 hdrop 这种类型，所以只能作为文件粘贴到资源管理器，别的软件（word之类）里面都不能直接粘。这个比较头疼，没有什么头绪。

**Comment by xiozf** [comment]
是JPG格式的照片。
原来如此，在资源管理器上粘贴成功了。我上面上传的图片显示成那样子应该是我所使用的第三方剪贴板管理软件本身的问题。

**Comment by YanxinTang** [comment]
v0.2.4 可以直接复制截图了。也可以直接粘贴到 word了。

**Comment by xiozf** [comment]
手机--->PC   没问题；  
PC--->手机   截图还是不行，运行复制的快捷指令没反应，测试文字没问题。看log里提示：msg="failed to decode bmp" error="bmp: unsupported BMP image" statusCode=500 。

**Comment by YanxinTang** [comment]
> 手机--->PC   没问题；  
> 
> PC--->手机   截图还是不行，运行复制的快捷指令没反应，测试文字没问题。看log里提示：msg="failed to decode bmp" error="bmp: unsupported BMP image" statusCode=500 。

你用的什么截图软件

**Comment by xiozf** [comment]
还真和截图软件有关啊。
用键盘Print Screen按键测试失败；
微信PC端测试失败；
Screenote测试失败（https://github.com/poerin/Screenote ）；
PicPick测试失败；
Snipaste测试成功。
