### ISSUE TITLE
[建议]在粘贴捷径增加两个类型

### ISSUE THREAD

**Issue by MatrixLau** [YanxinTang/clipboard-online#36]
我发现我iOS端复制的***文字***很多时候粘贴到PC会是`<内容>.txt`的形式
然后做了捷径测试，发现很多时候获取到的类型会是RTF跟文字，希望更新一下粘贴的捷径

**Comment by YanxinTang** [comment]
是在哪个应用复制的副文本呢

**Comment by MatrixLau** [comment]
> 是在哪个应用复制的副文本呢
*Telegram*的文本基本都是**RTF**，然后通过*捷径输入*的基本都是**文字**

**Comment by MatrixLau** [comment]
> 是在哪个应用复制的副文本呢

Telegram的文本基本都是RTF，然后通过捷径输入的基本都是文字

**Comment by YanxinTang** [comment]
你的系统语言是繁体的吗？

**Comment by MatrixLau** [comment]
> 你的系统语言是繁体的吗？

对，对应的```文本```为```文字```，```媒体```为```媒體```，```图像```为```影像```，```文件```为```檔案```

**Comment by YanxinTang** [comment]
捷径里没有加上繁体对应的类型，我明天更新一下。
