### ISSUE TITLE
有没有大佬知道，安卓端怎么直接推送当前剪切板内容到PC？

### ISSUE THREAD

**Issue by ffplayer** [YanxinTang/clipboard-online#38]
那个链接内的json导入HTTP Request Shortcuts里面，执行了之后，是会弹出输入框手动粘贴再发送的，比较麻烦。

有没有办法直接把安卓端当前剪切板内容推到PC呢？

**Comment by foolmos** [comment]
> 那个链接内的json导入HTTP Request Shortcuts里面，执行了之后，是会弹出输入框手动粘贴再发送的，比较麻烦。
> 
> 有没有办法直接把安卓端当前剪切板内容推到PC呢？

大佬，小众那个安卓端教程帖404了，大概猜一下，估计是用http request shortcuts导入json用，现在就缺个json模版抄作业呢😿求大佬共享一下～🙏

**Comment by ereere** [comment]
才用这个软件，HTTP Request Shortcuts 里面 点 “请求体/请求参数”，点请求体右面的“{}”，然后最下面的“编辑变量值”，然后右下角“+”号。里面有“剪切板内容”，HTTP Request Shortcuts 能直接获取 剪切板，点一下就发送了

**Comment by ffplayer** [comment]
> 才用这个软件，HTTP Request Shortcuts 里面 点 “请求体/请求参数”，点请求体右面的“{}”，然后最下面的“编辑变量值”，然后右下角“+”号。里面有“剪切板内容”，HTTP Request Shortcuts 能直接获取 剪切板，点一下就发送了

非常感谢！设置成功了，原来新版本已经支持剪切板变量了。


不过还有遇到一个问题是，发送的文本中，有换行的话，就会返回 400 bad request

不知道这个问题怎么解决呢？

我原本直接用的是 https://meta.appinn.net/t/topic/20322 这个，然后把变量改为剪切板变量。

但这个原本用输入框输入发送的方式，内容中包含回车就会发送失败。

**Comment by ffplayer** [comment]
> > 才用这个软件，HTTP Request Shortcuts 里面 点 “请求体/请求参数”，点请求体右面的“{}”，然后最下面的“编辑变量值”，然后右下角“+”号。里面有“剪切板内容”，HTTP Request Shortcuts 能直接获取 剪切板，点一下就发送了
> 
> 非常感谢！设置成功了，原来新版本已经支持剪切板变量了。
> 
> 不过还有遇到一个问题是，发送的文本中，有换行的话，就会返回 400 bad request
> 
> 不知道这个问题怎么解决呢？
> 
> 我原本直接用的是 https://meta.appinn.net/t/topic/20322 这个，然后把变量改为剪切板变量。
> 
> 但这个原本用输入框输入发送的方式，内容中包含回车就会发送失败。

自己找到解决办法了，创建的剪切板变量选上json编码就行了。
