### ISSUE TITLE
Safari中使用共享存在问题

### ISSUE THREAD

**Issue by jjijack** [YanxinTang/clipboard-online#39]
Safari中复制一段文字，通过共享-快捷指令发送是OK的。但是如果对网页使用右上角共享里的快捷指令（图中的发送至电脑剪切板），电脑剪切板里没有任何内容。
![IMG_1623](https://user-images.githubusercontent.com/32895850/169482511-d0f9985e-947f-4f3b-80a8-e03b65dbc6c3.jpeg)

**Comment by YanxinTang** [comment]
晚上回去看看

**Comment by jjijack** [comment]
刚刚发现其实是成功发送的，只不过通过这种方式发送的是.html网页而不是链接，所以黏贴到网页输入框里没有反应。虽然是个无伤大雅的小问题，但是如果作者大大能抽空修复一下就好了😂

**Comment by jjijack** [comment]
刚刚发现其实是成功发送的，只不过通过这种方式发送的是.html网页而不是链接，所以黏贴到网页输入框里没有反应。虽然是个无伤大雅的小问题，但是如果作者大大能抽空修复一下就好了😂

**Comment by YanxinTang** [comment]
试了 v2ex 和 github 都没复现。你是发送的哪个网站的页面？

**Comment by jjijack** [comment]
我试了学校的几个网站，以及Google、百度都是这样。Github和知乎则是html也没有

**Comment by YanxinTang** [comment]
我试了分享这几个站点的页面，都可以把网页的文字提取出来拷贝到剪切板。难道是版本问题？你的应用版本和 iOS 版本分别是多少。

**Comment by jjijack** [comment]
系统是iPad OS 15.5，软件是最新的0.2.7。之前的描述可能不太清楚，我提到分享文字正常只是表明是两边通信是没有问题的😂问题是分享网页的时候会有上述的问题，分享出的是html或者无反应，而不是一个链接

**Comment by YanxinTang** [comment]
明白了，等我这两天更新一下。
