### ISSUE TITLE
你好，我有一个云服务器，我想问可以升级走云服务器的代码吗？

### ISSUE THREAD

**Issue by Lee-huro** [YanxinTang/clipboard-online#48]
你好，我在想每到一个地方都要设置ssid会有点麻烦，所以可以在云服务器设置个端口，走云服务器，这样不论无线还是流量，有网就可以复制了。可以升级下吗？第一次写issue，还请担待。。

**Comment by YanxinTang** [comment]
内网穿透请用其他工具，如 nps, frp
