### ISSUE TITLE
建议完善快捷指令参数配置说明

### ISSUE THREAD

**Issue by lifangzheng** [YanxinTang/clipboard-online#51]
参考https://www.kejiwanjia.com/jiaocheng/zheteng/83030.html配置成功了，之前看readme不清楚在哪里设置SSID、IP、Authkey，可能是我不了解快捷指令，还是希望readme可以配上截图或者说得更清晰一些。

**Comment by fudingyu** [comment]
是的，作为一个程序员ssid的key和value我都没搞明白要怎么填？是要填wifi:wifi_name还是怎么回事
或者直接在备注里面说清楚 key = wifi name,value = ip.

**Comment by YanxinTang** [comment]
感谢，我链接到 readme
