### ISSUE TITLE
设置密钥后403，不设置就可以。

### ISSUE THREAD

**Issue by erikaemma** [YanxinTang/clipboard-online#55]
time="2022-09-22T22:54:50+08:00" level=warning clientIP=192.168.0.104 clientName=iPhone duration="961.4µs" method=GET path=/ statusCode=403

设置密钥后就这样，我设置的asdfghjkl1318

**Comment by YanxinTang** [comment]
1. 电脑跟手机的系统时间要一致，秒差不能大于  `authkeyExipredTimeout`  的值
2. `authkeyExipredTimeout` 值设置大一点
