### ISSUE TITLE
 可以适配老版本的捷径吗？

### ISSUE THREAD

**Issue by kakakuho** [YanxinTang/clipboard-online#58]
如题

在safari中输入网址，提示如下：
shortcut format too now(This shortcut cannot be opened because it was created on a newer version of the shortcuts app)

目前在使用的设备是iphone 7，ios版本12.3.1，shortcuts版本2.2.2;

因为苹果特性，更新的话老机型将会变得巨卡无比。而且iphone7不支持ios16。相应地，shortcuts在目前该ios版本号下，支持运行的最新版本是2.2.2。

作者是否考虑一些老旧苹果机型的适配，另外提供一个以旧版本制作的shortcuts捷径呢，万分感谢！

**Comment by YanxinTang** [comment]
这个不在考虑范围之内了。首先我没有旧版本的设备了已经，而且捷径写起来让我有点痛苦。
