### ISSUE TITLE
无法启动端口服务

### ISSUE THREAD

**Issue by 111413** [YanxinTang/clipboard-online#6]
本机内网IP是1.1.1.2
只有本机可以访问1.1.1.2:8086
内网的其他设备都无法访问

但是本机运行的其他服务，比如Charles
内网的其他设备都是可以连接的

尝试过更换端口，也没有作用

是内网IP段问题？或是win10精简版的问题么？

**Comment by YanxinTang** [comment]
有没有可能时防火墙导致的？把防火墙暂时关掉试试？

**Comment by 111413** [comment]
> 有没有可能时防火墙导致的？把防火墙暂时关掉试试？

家用PC，没有防火墙！

**Comment by 111413** [comment]
简单来说，本机开放的其他服务，内网的其他设备都可以连接！
唯独这个不可以！

但是服务明明是启动了的，因为本机可以访问:8086

**Comment by YanxinTang** [comment]
有可能是网段的问题（我不太确定），我这两天搭个环境测试一下。

**Comment by 111413** [comment]
> 有可能是网段的问题（我不太确定），我这两天搭个环境测试一下。

好的，等你答复，谢谢。

**Comment by MittWillson** [comment]
建议再次确认一下防火墙，在高级防火墙设置里有不同场景下的，全部都关闭试试

**Comment by 111413** [comment]
> 建议再次确认一下防火墙，在高级防火墙设置里有不同场景下的，全部都关闭试试

确实，来宾防火墙没关
关掉以后解决了

不好意思问一下，新版捷径在哪设置IP ， 不是SSID NAME吧

**Comment by YanxinTang** [comment]
SSID 列表的字典中添加值为文本的新项目，其中键为 SSID 的名称（可以只是其中一部分），值是IP

**Comment by 111413** [comment]
> SSID 列表的字典中添加值为文本的新项目，其中键为 SSID 的名称（可以只是其中一部分），值是IP

那有点奇怪，你的2个新版捷径，都是连接超时
但是手机是可以打开:8086的！

**Comment by YanxinTang** [comment]
ssid 是要区分大小写的，请确保填写正确。如果还是不行，建议扫描首页的二维码重新添加一下捷径。添加的时候按照导入问题的格式配置 ssid  和 ip

**Comment by 111413** [comment]
> ssid 是要区分大小写的，请确保填写正确。如果还是不行，建议扫描首页的二维码重新添加一下捷径。添加的时候按照导入问题的格式配置 ssid 和 ip

sorry，确保PC IP正确的，仍然是提示超时。

https://imgtu.com/i/gByhJU
https://imgtu.com/i/gBy4WF
https://imgtu.com/i/gByfiT

**Comment by YanxinTang** [comment]
ssid 填到 key 里面，类似这样
[![gBcIbR.png](https://z3.ax1x.com/2021/05/13/gBcIbR.png)](https://imgtu.com/i/gBcIbR)

**Comment by 111413** [comment]
> ssid 填到 key 里面，类似这样
> [![gBcIbR.png](https://camo.githubusercontent.com/8c9d33afac12c31726a170d425da33b11451135ee33e6aa5ec34f83ac18ba6c1/68747470733a2f2f7a332e617831782e636f6d2f323032312f30352f31332f6742634962522e706e67)](https://imgtu.com/i/gBcIbR)

成功，soory，太笨，遇到了2个问题

1，win10的来宾防火墙要关闭
2，路由ssid未设置
