### ISSUE TITLE
快捷指令完成，但是并没有复制成功

### ISSUE THREAD

**Issue by avegetablechicken** [YanxinTang/clipboard-online#60]
复制和粘贴的快捷指令都显示对号，但是两个方向都无法复制。
server段的debug log如下
```
time="2022-11-09T15:55:22+08:00" level=debug msg="start http server"
time="2022-11-09T15:55:22+08:00" level=debug msg="start app"
```
temp目录下为空

设备是iPhone11 (iOS16.1)和windows11 21H2

**Comment by YanxinTang** [comment]
确认一下快捷指令中的 ip 和 端口 是否正确？

日志里面显示正常启动了，但是并没有收到请求。

**Comment by avegetablechicken** [comment]
> 确认一下快捷指令中的 ip 和 端口 是否正确？
> 
> 日志里面显示正常启动了，但是并没有收到请求。

重启服务器端几次就好了
