### ISSUE TITLE
ios16.2 - win11，从PC复制可以，但是从移动端复制提示无法连接服务器

### ISSUE THREAD

**Issue by Chao-Sky** [YanxinTang/clipboard-online#63]
ios16.2 - win11，从PC复制可以，但是从移动端复制提示无法连接服务器

**Comment by Chao-Sky** [comment]
电脑访问 http://127.0.0.1:8086，
手机访问 http://<pc_ip>:8086
手机跟电脑均有反应，提示：{"error":"接口版本不匹配，请升级您的捷径"}

**Comment by Chao-Sky** [comment]
防火墙均关闭，且重启了PC

**Comment by YanxinTang** [comment]
![图像](https://github.com/YanxinTang/clipboard-online/assets/15326923/1f99089a-f6aa-4433-8f29-5d2db4e2aacf)

看一下隐私，这里的网络权限请确保允许。

**Comment by Chao-Sky** [comment]
![A1E4F9A6-1922-4EFB-91AD-5B5EBD9F15FD](https://github.com/YanxinTang/clipboard-online/assets/45475000/6c749cf7-68a2-457c-bfb7-82ab940c7157)
我发现了与你的不同，我这里没有显示允许使用ip地址，但是我也不知道该怎么办

**Comment by YanxinTang** [comment]
![image](https://user-images.githubusercontent.com/15326923/239106311-79890b68-a0b7-4796-a573-03f784f29712.jpeg)

看一下IP列表有没有配置正确。

**Comment by Chao-Sky** [comment]
![1AB03165-8D14-4B03-80C5-D8D1927AC941](https://github.com/YanxinTang/clipboard-online/assets/45475000/b6133bba-5a67-4f80-a1b5-c1e2bdd93dde)
配置是没问题的
![690DE9FB-9700-4446-9AF8-E7376E374A2C](https://github.com/YanxinTang/clipboard-online/assets/45475000/d4660dd8-15d6-4ea6-91c6-0f67fef8c679)
我发现这里获取不到正确的值，是不是因为我的wifi打开了双频合一的原因，获取不到正确的wifi名称，快捷指令能打断点调试吗？

**Comment by YanxinTang** [comment]
![image](https://user-images.githubusercontent.com/15326923/239111573-fd1ed798-f638-4c4a-8183-0d7c139d3acb.png)

可以插入快速查看指令来调试。

**Comment by Chao-Sky** [comment]
好的 感谢，等我回到家，我连上家里的wifi调试一下ios获取到的网络名称

**Comment by QuarkPixel** [comment]
我也遇到了同样的问题？貌似是快捷指令的bug，给的是http，输出的却是https
![A5A87E83F68279D633129AE9A986CC4E](https://github.com/YanxinTang/clipboard-online/assets/65812149/dd54a7d9-fff9-429d-a395-eff909cf03cf)
![FFBCF7BA3A41A75B5BE74EE42E687D3F](https://github.com/YanxinTang/clipboard-online/assets/65812149/37e93f4b-7337-4e5a-908a-3e78927c9d0e)

**Comment by YanxinTang** [comment]
系统是 16.5 吗？

**Comment by QuarkPixel** [comment]
> 

16.4 & 16.5 皆测试过，不行

**Comment by YanxinTang** [comment]
我升级前后都可以，您这边跟楼上是同一问题吗？

**Comment by QuarkPixel** [comment]
提示的内容是一样的，但是我这边的问题在从PC复制和从移动端复制皆提示无法连接服务器，用浏览器访问是可以访问的到的
