### ISSUE TITLE
接口版本不匹配，请升级您的捷径

### ISSUE THREAD

**Issue by suifengtec** [YanxinTang/clipboard-online#7]
`{"error":"接口版本不匹配，请升级您的捷径"}`

嗯，不错的代码，可是不管是运行下载的exe,还是运行本地编译的exe,打开`127.0.0.1:8086`之后,都见到了上面的错误，然后呢？

**Comment by YanxinTang** [comment]
扫描一下首页的二维码，使用最新的捷径来操作
