### ISSUE TITLE
"error": "接口版本不匹配，请升级您的捷径"

### ISSUE THREAD

**Issue by rosebudgrave** [YanxinTang/clipboard-online#75]
![image](https://github.com/YanxinTang/clipboard-online/assets/45752666/363283b4-7e3d-46fd-81bf-340fe4c206d0)
![image](https://github.com/YanxinTang/clipboard-online/assets/45752666/6419c486-bd55-4967-9832-1dd6493866c2)

**Comment by rosebudgrave** [comment]
这个要什么接口版本?

**Comment by cosir888** [comment]
请求头必填项没设置
'X-API-Version':1

**Comment by rosebudgrave** [comment]
> 请求头必填项没设置 'X-API-Version':1

有用,感谢 可以访问了

**Comment by Barmaid1076** [comment]
> 请求头必填项没设置 'X-API-Version':1

请问这个要怎么设置？

**Comment by YanxinTang** [comment]
> > 请求头必填项没设置 'X-API-Version':1
> 
> 
> 
> 请问这个要怎么设置？

快捷指令内有一个步骤 “获取 URL 内容”，展开可以看到需要的请求头，'X-API-Version' 是其中一个。
![image](https://github.com/YanxinTang/clipboard-online/assets/15326923/f3bc2d6b-55a3-4013-9bc6-fdce124a904b)

**Comment by Barmaid1076** [comment]
> > > 请求头必填项没设置 'X-API-Version':1
> > 
> > 
> > 请问这个要怎么设置？
> 
> 快捷指令内有一个步骤 “获取 URL 内容”，展开可以看到需要的请求头，'X-API-Version' 是其中一个。 ![image](https://private-user-images.githubusercontent.com/15326923/341252740-f3bc2d6b-55a3-4013-9bc6-fdce124a904b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NjA5ODYsIm5iZiI6MTcxODg2MDY4NiwicGF0aCI6Ii8xNTMyNjkyMy8zNDEyNTI3NDAtZjNiYzJkNmItNTVhMy00MDEzLTliYzYtZmRjZTEyNGE5MDRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA1MTgwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhMDM0OWM2Y2JlM2RlMTkyZDFmNzdjMThlYjBlY2QyMjAxZmY5ODEwOTYxMGI1ZjAxNDdjODQ5MzM3MWZiMmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.In0sscGtSG78FBP9DyoOZ-Sro_LmP3nIjuRspAwts8A)

谢谢！我找到展开了以后，里面已经填上了1，但我还是会收到这个错误是为什么呢？
我还想问一下
1. Get windows clipboard
2. Set windows clipboard
这两个设置是要设置什么？
比方说
// 200 ok

{
  "type": "text",
  "data": "clipboard text on the server"
}

{
  "type": "file",
  "data": [
    {
      "name": "filename",
      "content": "base64 string of file bytes"
    }
    ...
  ]
}
我们是要自己新建一个json文件，然后放到一个地方吗？

**Comment by YanxinTang** [comment]
> 1. 还会收到错误

Windows 程序是最新的吗？

> 2. Get windows clipboard/Set windows clipboard

这个是快捷指令跟 Windows 程序交互的 api 定义格式，可以不用理会。

**Comment by Barmaid1076** [comment]
是最新的,刚刚下载的

> > 1. 还会收到错误
> 
> Windows 程序是最新的吗？
> 
> > 2. Get windows clipboard/Set windows clipboard
> 
> 这个是快捷指令跟 Windows 程序交互的 api 定义格式，可以不用理会。



> > 1. 还会收到错误
> 
> Windows 程序是最新的吗？
> 
> > 2. Get windows clipboard/Set windows clipboard
> 
> 这个是快捷指令跟 Windows 程序交互的 api 定义格式，可以不用理会。



> > 1. 还会收到错误
> 
> Windows 程序是最新的吗？
> 
> > 2. Get windows clipboard/Set windows clipboard
> 
> 这个是快捷指令跟 Windows 程序交互的 api 定义格式，可以不用理会。

**Comment by Barmaid1076** [comment]
> > 1. 还会收到错误
> 
> Windows 程序是最新的吗？
> 
> > 2. Get windows clipboard/Set windows clipboard
> 
> 这个是快捷指令跟 Windows 程序交互的 api 定义格式，可以不用理会。

是最新的,刚刚下载的

**Comment by YanxinTang** [comment]
再仔细检查一下快捷指令

1. 复制/粘贴的 URL请求都需要这个请求头
2. 检查一下拼写对不对，有没有包含空格之类的，以及不要带引号

**Comment by Barmaid1076** [comment]
> 再仔细检查一下快捷指令
> 
> 1. 复制/粘贴的 URL请求都需要这个请求头
> 2. 检查一下拼写对不对，有没有包含空格之类的，以及不要带引号

把两个快捷方式都重新装了一遍，然后重新填入了3个变量，但是还是无法复制粘贴，PC访问网页还是会出现标题的错误
authkey我在pc config文件里, 还有两个快捷方式中都填的是同样的4个英文字母
网络名称和网址，我都按照教程里面填到快捷方式里面去了

还有什么是要需要设置的吗？

**Comment by YanxinTang** [comment]
> PC访问网页还是会出现标题的错误

这个接口是用于快捷指令的，得到这个响应是正常现象

先测试手机到电脑的网络是否正常；
其次如果设置 authkey 需要保证手机跟电脑的时间相差在 30s 内，没设置可以跳过检查

**Comment by Barmaid1076** [comment]
> 先测试手机到电脑的网络是否正常；
> 其次如果设置 authkey 需要保证手机跟电脑的时间相差在 30s 内，没设置可以跳过检查

谢谢。我还以为authkey是必须要设置的
