### ISSUE TITLE
请求更新支持与安卓之间的剪贴板同步代码

### ISSUE THREAD

**Issue by SwePolice** [YanxinTang/clipboard-online#77]
根据文档中的跳转链接：https://meta.appinn.net/t/topic/20322。
设置之后安卓端HTTP Shortcuts可正常获取到PC端的剪贴板内容，但是推送手机端的剪贴板内容到PC端的时候，会弹出要求输入发送内容的对话框，并不能无感体验。希望开发者能针对安卓端HTTP Shortcuts更新一下相应代码。谢谢了

**Comment by YanxinTang** [comment]
报歉，我没有安卓设备，安卓端HTTP Shortcuts 也不是我在维护。
