### ISSUE TITLE
请问我有一台iPhone 3台win电脑，每台电脑的端口都是这个：8086吗  还是说每台电脑设一个不同的端口呢？那个config文件里面的参数是可以修改的吗，必须和快捷方式同步对等修改才能生效吗？三台电脑都是一个设置吗，如果其中两台电脑同时开机，手机里复制，那两台电脑会同时收到传送并可以粘贴吗？

### ISSUE THREAD

**Issue by IVY01med** [YanxinTang/clipboard-online#78]

**Comment by YanxinTang** [comment]
1. 3台电脑用相同的端口
2. config里的参数必须跟快捷指令同步修改
3. 可以创建3条快捷指令，分别命名为电脑A，电脑B，电脑C，快捷指令内的 ip 与电脑的 ip 对应。

**Comment by IVY01med** [comment]
我的两台笔记本电脑可以了，成功了，就是台式机不能成功。方法是一样的。不知为什么。

**Comment by komazhou** [comment]
> 我的两台笔记本电脑可以了，成功了，就是台式机不能成功。方法是一样的。不知为什么。

试试检查一下台式机上面是专用网络还是公用网络。

**Comment by YanxinTang** [comment]
> 我的两台笔记本电脑可以了，成功了，就是台式机不能成功。方法是一样的。不知为什么。

先排除一下网络的问题。
