### ISSUE TITLE
从ios设置Windows剪贴板失败

### ISSUE THREAD

**Issue by siwei-li** [YanxinTang/clipboard-online#8]
ios端可以成功 get 剪贴板内容，但是无法用 post 请求设置Windows端剪贴板内容
log.txt中 post 请求的 statusCode=200
就不知道是怎么回事了，大神东西做得很好，求助呀

time="2021-09-02T21:52:25-07:00" level=info msg="set clipboard file" paths="[C:\\Users\\xxxxxx\temp\\Clipboard Sep 2, 2021 at 21.52.52]" requestID=2015796113853353331
time="2021-09-02T21:52:25-07:00" level=info clientIP=192.168.xxxx clientName="xxx's iPhone" duration=6.9944ms method=POST path=/ requestID=2015796113853353331 statusCode=200

**Comment by siwei-li** [comment]
发现post之后 Windows端剪贴板里是一个剪贴板文件而不是文本内容，就是放在temp文件夹里的文件，不知道为什么没有成功从里面提取文本到剪贴板里

**Comment by YanxinTang** [comment]
手机上复制的是文本吗？
看请求是手机上复制了一个文件之后，运行了粘贴的快捷指令

**Comment by siwei-li** [comment]
> 手机上复制的是文本吗？
> 看请求是手机上复制了一个文件之后，运行了粘贴的快捷指令

确实都是文本，试了在备忘录和网页随便复制几个字这样，不知道为什么剪贴板里都是文件

![image](https://user-images.githubusercontent.com/46750682/131956090-e0071101-96c3-450a-9047-bd7a31c6989f.png)
（上面是剪贴板软件Ditto里显示的）

**Comment by siwei-li** [comment]
又试了一下，temp文件夹里的文件是Clipboard Sep 2,2021  at 22.54.txt
里面的文本内容就是手机上复制的内容

**Comment by YanxinTang** [comment]
拷备的富文本被捷径识别成文件了。请问一下你是从什么软件拷的？

**Comment by siwei-li** [comment]
在 ios自带的备忘录，chrome 的网页还有其他的笔记软件都试过，如果有格式就会拷贝成 .rtf 文件，没有格式就是 .txt 文件

**Comment by YanxinTang** [comment]
![IMG_2475](https://user-images.githubusercontent.com/15326923/132084583-8b3d7a5b-e2da-42a1-bcb1-781cddfba157.png)

你新建一个这个捷径看看剪切板内是什么类型的内容。
正常情况下，富文本应该是 `多信息文本` ，普通文本应该是 `文本`

还有就是确保你的捷径和 windows 程序都是最新的

**Comment by siwei-li** [comment]
![image](https://user-images.githubusercontent.com/46750682/132087434-b6029cc7-748e-4a4b-a9cf-3a959f4d287f.png)

悲伤，两边软件确实都是最新的了

**Comment by YanxinTang** [comment]
![IMG_2477](https://user-images.githubusercontent.com/15326923/132091438-c1a14e7b-be2a-4ac9-b8c8-fc06e613b638.jpeg)

我知道是什么问题了，因为你用的英文的系统，这里匹配的时候只匹配了中文环境下的类型，你可以手动在这个位置 `添加新项目` 临时解决一下

```
Text: text
```

**Comment by siwei-li** [comment]
非常感谢呀！问题解决了
