### ISSUE TITLE
添加中继服务器机制，实现跨网络剪切板共享

### ISSUE THREAD

**Issue by page-4everl** [YanxinTang/clipboard-online#82]
目前 clipboard-online 要求设备必须在同一局域网内才能共享剪切板内容，或者需要复杂的端口转发设置才能通过公网访问。
建议增加中继服务器机制，让任意网络环境下的设备都能方便地共享剪切板内容。通过服务器中转，则无需关心网络环境，只需要简单的配对过程就能实现设备互联，特别是不再需要使用本地电脑作为服务端。
中继服务器的核心功能是负责设备之间的信息中转。当用户在设备A复制内容后，内容会先发送到中继服务器，再由服务器转发给设备B。为了确保数据安全，建议整个传输过程采用端到端加密，中继服务器无法查看具体内容，且不永久储存内容。
期待开发者能考虑实现这个建议，谢谢！

**Comment by YanxinTang** [comment]
非常感谢您的建议。

此项目真实源于我个人在工作和生活中的需求，但正如您看到的，它已经很久没有更新了，原因有二：

1. 现在的工作环境用不到了
2. 捷径的编程方式，操作起来让我有点疲惫

您的建议非常中肯实用，但确实不会成为短期开发的目标。
